dist: xenial
language: python

cache: pip

branches:
  only:
    - master

python:
  - 3.6
  - 3.7
  - 3.8

jobs:
  include:
    - stage: Check
      python: 3.7
      script: scripts/check
    - stage: Docs
      python: 3.7
      script: scripts/docs

script:
  - scripts/test

after_script:
  - if [ -f .coverage ]; then
    python -m pip install codecov;
    codecov --required;
    fi
